### ISSUE TITLE
performance is great, no?

### ISSUE THREAD

**Issue by rchikhi** [natir/fastmap#1]
Hi Pierre,

Am doing lots of Rust these days, and after having coded https://github.com/rchikhi/rust-parallelfastx, I realized that https://github.com/natir/in_place_fastx/ is similar (and more engineered). You confirm?

The principle of `rust-parallelfastq` is to naively cut the file in N blocks, adjust the block beginning so that they match the beginning of a FASTX entry, then run a fastx parser on each block.

Testing `in_place_fastx` with the following example program:

https://github.com/rchikhi/in_place_fastx/blob/main/src/main.rs

Results on a 39GB fasta file, over a very fast cluster RAID-like disk system:

| Time (10 threads) | rust-parallelfastx | in_place_fastx | needletail | wc -l  |
|-------------------|---------------------|----------------|------------|--------|
| 10x human HiFi   | 3.6 s               | 3.5 s          | 10.9 s     | 10.4 s |

Command lines:

```
rust-parallelfastx$ \time cargo run --release -- ~/data/human-mdbg/simulated-chm13v2.0-10X.fa 10
Parsing input FASTX file /pasteur/appa/homes/rchikhi/data/human-mdbg/simulated-chm13v2.0-10X.fa (10 threads)
FASTX parsed in 3.655991326s.
15.58user 5.58system 0:04.18elapsed 505%CPU (0avgtext+0avgdata 33208996maxresident)k

wc$ \time wc -l ~/data/human-mdbg/simulated-chm13v2.0-10X.fa
2980820 /pasteur/appa/homes/rchikhi/data/human-mdbg/simulated-chm13v2.0-10X.fa
0.93user 9.44system 0:10.42elapsed 99%CPU (0avgtext+0avgdata 2016maxresident)k # (cpu bound)

in_place_fastx$ \time cargo run --release -- ~/scratch/hg002-mdbg/hifimap/simulated-chm13v2.0-10X.fa
 in_place_fastx parsed in 3.49228476s.
now needletail:
needletail parsed in 10.978545649s.
31.32user 17.08system 0:20.83elapsed 232%CPU (0avgtext+0avgdata 317320maxresident)k
```

a+

Rayan

**Comment by jianshu93** [comment]
Hello Rayan,

I have a not a fasta file error, which is apparently a fasta file:

Finished release [optimized + debuginfo] target(s) in 0.79s
     Running `target/release/in_place_fastx /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_G/projects/pico/reads/05.trimmedFastA/pico127.CoupledReads.fa`
Error: NotAFastaFile

real	0m5.882s
user	0m0.186s
sys	0m4.605s



[jzhao399@atl1-1-02-003-30-2 in_place_fastx]$ head /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_G/projects/pico/reads/05.trimmedFastA/pico127.CoupledReads.fa
>pico127-1/1
CTTTGGATATCACTTTCGAGAGCTTTGTTGAGGATGTGGACGCAGTTGTAAATGATGCAAAGATTAATAAATTTCCAATATTA
>pico127-1/2
ATTGATGTGGCAAAAAACTGTCTAAAAGCGGGGTTCTCATCTTCCCATCCACTTAAAATCATGGTTTGTTCCATCTTACTTTTAGATTCATAAGTAGGATCATTTCTTTGACCTTTTCCTCTAGCA
>pico127-2/1
TTATCAGAATTTAGTTTGTAAGTATGTCTTGCAGCACCAGAAATACATGGTTTTTAAACGGTTGTTTCACAATTCATTTTTGTATGAAGATCTTCTAGATTACAATCGGTACCTTTTTCAATAAATAGTGTTTCAGC
>pico127-2/2
TTCAGGACAACATGGGATTATTTTGATGATTTCGATGAGTTTTCCAATTGGTTAAATGACGTCTCAAAAGTCACAACACTTATGAATTCAGAAGCTACCGTTAGATGGAATATTGACAAACATTATTTAAAAGACCTTAAA


Thanks,

Jianshu

**Comment by rchikhi** [comment]
Hi Jianshu, 
please move this reply to its own issue, this thread is about performance. Also, I am not the developer of this repository.

**Comment by natir** [comment]
Hi @jianshu93 can you open another issue please. And your file not look like a fasta `>` at begin of comment line is missing.

I can confirm method of my in_place_fastx and your rust-parallelefastq are realy similar.
